In [1]:
import gymnasium as gym
import numpy as np

env=gym.make("FrozenLake-v1",is_slippery=True)

# Exercice 1

In [2]:
#Instruction 2
print(f"Espace d'etats: {env.observation_space}")
print(f"Espace d'actions: {env.action_space}")

Espace d'etats: Discrete(16)
Espace d'actions: Discrete(4)


In [3]:
#Instruction 3 & 4
for _ in range(100):
    env.reset()
    action=env.action_space.sample()
    observations,reward,done,_,_=env.step(action)

    print(f"Action : {action}, Observations : {observations}, Reward : {reward}")



Action : 1, Observations : 0, Reward : 0.0
Action : 0, Observations : 0, Reward : 0.0
Action : 3, Observations : 0, Reward : 0.0
Action : 1, Observations : 4, Reward : 0.0
Action : 0, Observations : 4, Reward : 0.0
Action : 1, Observations : 4, Reward : 0.0
Action : 3, Observations : 1, Reward : 0.0
Action : 1, Observations : 0, Reward : 0.0
Action : 0, Observations : 0, Reward : 0.0
Action : 3, Observations : 0, Reward : 0.0
Action : 0, Observations : 0, Reward : 0.0
Action : 2, Observations : 1, Reward : 0.0
Action : 0, Observations : 4, Reward : 0.0
Action : 2, Observations : 1, Reward : 0.0
Action : 1, Observations : 1, Reward : 0.0
Action : 0, Observations : 0, Reward : 0.0
Action : 0, Observations : 0, Reward : 0.0
Action : 2, Observations : 0, Reward : 0.0
Action : 2, Observations : 1, Reward : 0.0
Action : 1, Observations : 1, Reward : 0.0
Action : 3, Observations : 0, Reward : 0.0
Action : 1, Observations : 0, Reward : 0.0
Action : 1, Observations : 0, Reward : 0.0
Action : 2,

# Exercice 2

In [4]:
num_states = env.observation_space.n   
num_actions = env.action_space.n       


q_table = np.zeros((num_states, num_actions))


print("Q-Table initiale avant apprentissage :\n")
print(q_table)


print("\n Vérification : chaque état doit avoir une liste de", num_actions, "valeurs (une pour chaque action) :")
for state in range(num_states):
    print(f"État {state}: {q_table[state]}")


Q-Table initiale avant apprentissage :

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Vérification : chaque état doit avoir une liste de 4 valeurs (une pour chaque action) :
État 0: [0. 0. 0. 0.]
État 1: [0. 0. 0. 0.]
État 2: [0. 0. 0. 0.]
État 3: [0. 0. 0. 0.]
État 4: [0. 0. 0. 0.]
État 5: [0. 0. 0. 0.]
État 6: [0. 0. 0. 0.]
État 7: [0. 0. 0. 0.]
État 8: [0. 0. 0. 0.]
État 9: [0. 0. 0. 0.]
État 10: [0. 0. 0. 0.]
État 11: [0. 0. 0. 0.]
État 12: [0. 0. 0. 0.]
État 13: [0. 0. 0. 0.]
État 14: [0. 0. 0. 0.]
État 15: [0. 0. 0. 0.]


# Exercice 3

In [15]:
import random

alpha = 0.1  # Taux d'apprentissage
gamma = 0.99  # Facteur de discount
epsilon = 1.0  # Exploration initiale
epsilon_decay = 0.995  # Décroissance d'epsilon
num_episodes = 100  # Nombre d'épisodes


for episode in range(num_episodes):
    state, _ = env.reset()
    done = False

    while not done:
        
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()  # Exploration (action aléatoire)
        else:
            action = np.argmax(q_table[state, :])  # Exploitation (meilleure action connue)

       
        next_state, reward, done, _, _ = env.step(action)

       
        q_table[state, action] = q_table[state, action] + alpha * (
            reward + gamma * np.max(q_table[next_state, :]) - q_table[state, action]
        )

        state = next_state  # Mise à jour de l'état


   
    if episode % 10 == 0:
        print(f"Épisode {episode}/{num_episodes} terminé - epsilon : {epsilon:.4f}")

env.close()

print("\n Q-Table après apprentissage :")
print(q_table)


Épisode 0/100 terminé - epsilon : 1.0000
Épisode 10/100 terminé - epsilon : 1.0000
Épisode 20/100 terminé - epsilon : 1.0000
Épisode 30/100 terminé - epsilon : 1.0000
Épisode 40/100 terminé - epsilon : 1.0000
Épisode 50/100 terminé - epsilon : 1.0000
Épisode 60/100 terminé - epsilon : 1.0000
Épisode 70/100 terminé - epsilon : 1.0000
Épisode 80/100 terminé - epsilon : 1.0000
Épisode 90/100 terminé - epsilon : 1.0000

 Q-Table après apprentissage :
[[0.05967139 0.05947609 0.05567934 0.05572015]
 [0.04260804 0.0351435  0.03913766 0.05377313]
 [0.05618619 0.04636775 0.05266726 0.04633461]
 [0.02234311 0.0208033  0.02653574 0.03950699]
 [0.0648241  0.05154951 0.04539273 0.03377214]
 [0.         0.         0.         0.        ]
 [0.03022443 0.02788873 0.07377217 0.01230571]
 [0.         0.         0.         0.        ]
 [0.04962215 0.05429796 0.06940565 0.07398667]
 [0.09921859 0.1048554  0.10519926 0.06354616]
 [0.14828414 0.1350736  0.08734151 0.04717652]
 [0.         0.         0.      

# Exercice 4

In [16]:
num_test_episodes=100
successes=0
for episode in range(num_test_episodes):
    state, _ = env.reset()
    done = False

    while not done:
        action = np.argmax(q_table[state, :])  # Sélectionner l'action optimale
        next_state, reward, done, _, _ = env.step(action)
        state = next_state

        if reward == 1:
            successes += 1

success_rate = successes / num_test_episodes * 100
print(f"\n L'agent a atteint l'objectif {successes} fois sur {num_test_episodes} essais.")
print(f" Taux de réussite : {success_rate:.2f}%")

env.close()


 L'agent a atteint l'objectif 19 fois sur 100 essais.
 Taux de réussite : 19.00%
